[package]
name = "uni-rpc"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true

[dependencies]
discord-rich-presence = "1.1.0"
dotenvy = "0.15.7"
reqwest = { version = "0.13.4", features = ["json", "query"] }
scraper = "0.27.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
